version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - sbt-deps-{{ checksum "build.sbt" }}
            - sbt-deps-
      - run: sbt update
      - save_cache:
          paths: [ "~/.m2", "~/.ivy2", "~/.cache/coursier" ]
          key: sbt-deps-{{ checksum "build.sbt" }}
      - run: sbt test